### ISSUE TITLE
部署完毕  用微信扫了二维码 登录一下就报错了

### ISSUE THREAD

**Issue by 3858809** [code-innovator-zyx/wechat-gptbot#17]
2024/09/08 12:14:41 扫码成功,请在手机上确认登录
panic: login forbidden

goroutine 1 [running]:
main.main()
        /home/wxjqr/wechat-gptbot/app.go:35 +0x460
项目运行失败，请检查错误信息
make: *** [makefile:37: local] Error 1

不知道为什么 请教一下大佬

**Comment by code-innovator-zyx** [comment]
> 2024/09/08 12:14:41 扫码成功,请在手机上确认登录 panic: login forbidden
> 
> goroutine 1 [running]: main.main() /home/wxjqr/wechat-gptbot/app.go:35 +0x460 项目运行失败，请检查错误信息 make: *** [makefile:37: local] Error 1
> 
> 不知道为什么 请教一下大佬
你是不是用的新号登录，账号被限制登录
