### ISSUE TITLE
Error: 私聊对单正常，群聊报错下标越界，信息见详情

### ISSUE THREAD

**Issue by VergilWu** [code-innovator-zyx/wechat-gptbot#2]
感谢作者开源~
```shell
panic: runtime error: slice bounds out of range [7:5]

goroutine 13 [running]:
wechat-gptbot/core/handler.checkMessageType(0xc00013ea00)
        /root/wechat-gptbot/core/handler/handler.go:138 +0x491
wechat-gptbot/core/handler.NewMessageMatchDispatcher.func2(0x0?)
        /root/wechat-gptbot/core/handler/handler.go:39 +0x13
github.com/eatmoreapple/openwechat.(*MessageMatchDispatcher).Dispatch(0xc000024360, 0xc00013ea00)
        /root/go/pkg/mod/github.com/eatmoreapple/openwechat@v1.4.6/message_handle.go:113 +0xa6
main.main.(*MessageMatchDispatcher).AsMessageHandler.func1(0xc00015c000?)
        /root/go/pkg/mod/github.com/eatmoreapple/openwechat@v1.4.6/message_handle.go:237 +0x1d
github.com/eatmoreapple/openwechat.(*Bot).syncCheck(0xc00015c000)
        /root/go/pkg/mod/github.com/eatmoreapple/openwechat@v1.4.6/bot.go:266 +0x273
github.com/eatmoreapple/openwechat.(*Bot).webInit.func1()
        /root/go/pkg/mod/github.com/eatmoreapple/openwechat@v1.4.6/bot.go:183 +0x58
created by github.com/eatmoreapple/openwechat.(*Bot).webInit in goroutine 1
        /root/go/pkg/mod/github.com/eatmoreapple/openwechat@v1.4.6/bot.go:178 +0x379
```

**Comment by VergilWu** [comment]
./core/handler/handler.go:138
`msg.Content = msg.Content[len("@年年"):]`
此处加到全局变量中应该就好了

**Comment by code-innovator-zyx** [comment]
> ./core/handler/handler.go:138 `msg.Content = msg.Content[len("@年年"):]` 此处加到全局变量中应该就好了

抱歉，这里之前自己写进自己的项目了，已经修复成了读取群消息变量，可以重新拉一下新的代码

**Comment by code-innovator-zyx** [comment]
新的代码已经提交
